### ISSUE TITLE
How do i auto reconnect?

### ISSUE THREAD

**Issue by Mathiaszero** [MattCrook/python_sockets_multi_threading#1]
For example, I stopped server then started it again, but the server did not pick up the client that still has socket running. How would I make a reconnect function/ feature? I'm open to general or specific guidance, thanks in advance and a really good project

**Comment by MattCrook** [comment]
Glad you found this useful! To be honest that is a good question, I haven't looked at this particular project in quite a while. And I know it still has some small bugs (such as rather that `SERVER` being dynamic, sometimes it only works if you hardcode the localhost IP of `127.0.0.1`). 

But, as far as the functionality of stopping and starting the server and it picking up the clients still running, that might be something you can take and run with to try and figure out! I don't think I got that far when I was doing this, and only expected a server to be running, and to start that first....and then be able to connect multiple clients. And didn't get further than that basic functionality. Would have liked to refine this a bit more to make that work, and make client to client messages and storing them and keeping them up to date work better, but stopped at the basic mvp for this as it was just a quick project for me to play with lower level python things. If you end up making some sort of reconnect function/ feature, let me know would love to see what you come up with. 🙂
